### ISSUE TITLE
vCenter() incorrectly alters the anchor point.

### ISSUE THREAD

**Issue by MaruthiBasava** [layoutBox/PinLayout#190] opened 2019-03-21 03:22 UTC
<img width="378" alt="Screen Shot 2019-03-20 at 11 18 20 PM" src="https://user-images.githubusercontent.com/22989905/54731820-ced00f00-4b66-11e9-9af3-49ffa59fa733.png">
<img width="459" alt="Screen Shot 2019-03-20 at 11 18 29 PM" src="https://user-images.githubusercontent.com/22989905/54731824-d2639600-4b66-11e9-827c-9a39765a8534.png">

Box 1 is Red 
Box 2 is Blue 
Box 4 is Pink. 

As you can see, the center anchor point of box4 should be on the bottom-right of box2, but its way off. I tested it without vCenter, and it worked perfectly.

**Comment by lucdion** [comment] 2019-03-26 22:19
@MaruthiBasava, could you show me your view's initialization codes (ref: addSubView, ...). There is maybe an issue, but I'm unable to reproduce your issue.

**Comment by lucdion** [comment] 2019-03-27 00:00
If you could share the whole UIViewController class, it would be even better.

**Comment by MaruthiBasava** [comment] 2019-03-30 16:29
```swift 
import UIKit
import PlaygroundSupport

class ViewController: UIViewController {
    
    lazy var box1 : UIView = {
        let v = UIView()
        v.backgroundColor = .red
        return v
    }()
    
    lazy var box2 : UIView = {
        let v = UIView()
        v.backgroundColor = .blue
        return v
    }()
    
    lazy var box3 : UIView = {
        let v = UIView()
        v.backgroundColor = .green
        return v
    }()
    
    lazy var box4 : UIView = {
        let v = UIView()
        v.backgroundColor = .red
        v.alpha = 0.5
        return v
    }()
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .white
        
        view.addSubview(box1)
        view.addSubview(box2)
        view.addSubview(box3)
        view.addSubview(box4)
        
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
            box2.pin.left(to: box1.edge.right)
            .vCenter(to: view.edge.vCenter).size(100).marginLeft(10)
            box4.pin.center(to: box2.anchor.bottomRight).size(20)
    
    }
    
}



PlaygroundPage.current.liveView = ViewController()


```

**Comment by MaruthiBasava** [comment] 2019-03-30 16:30
Run this in the playground.

**Comment by lucdion** [comment] 2019-03-30 19:30
There is some limitation of using PinLayout in Playgrounds. See 
https://github.com/layoutBox/PinLayout/blob/master/docs/xcode_playground.md

Issues was previously fixed by calling `layout()` method, but looks like there is new issues 😕

**Comment by MaruthiBasava** [comment] 2019-03-31 20:39
Actually you're right! calling `layout()` fixed my issue. Thank you so much! 
Also what are other issues that may be present within the Playgrounds? My company is currently prototyping the UI on playground for efficiency, so I would love to be aware of it. Thank you once again.

**Comment by lucdion** [comment] 2019-04-01 13:37
Good to know, that it fixed the issue, because I was scared that there was other issue with playgrounds. ARC behave differently in playgrounds, it doesn't release object immediately, but delay their destruction.

**Closed by lucdion** 2019-04-01 13:37 UTC
